# Generated by Django 4.0.1 on 2022-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email1', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('gun_buying', models.CharField(max_length=122)),
                ('payment_mode', models.CharField(max_length=122)),
            ],
        ),
    ]
