# Generated by Django 4.0.1 on 2022-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('buyer_email', models.CharField(max_length=122)),
                ('payment_mode', models.CharField(max_length=122)),
                ('payment_suffix', models.CharField(max_length=122)),
                ('gun_name', models.CharField(max_length=122)),
                ('cost', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
