# Generated by Django 4.0.1 on 2022-01-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_costumers_costumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
